name: Python Application CI

# Trigger the workflow on pushes or pull requests to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step 3: Install dependencies and run the project using Makefile
    - name: Install dependencies and run the project
      run: |
        make install  # Install dependencies
        make run &     # Start the Flask app
        sleep 10       # Wait for the server to start up
